DEBUG 2025-07-19 21:30:14.855 UTC: 	 CRAB Client version: v3.250522
DEBUG 2025-07-19 21:30:14.855 UTC: 	 Running on: Linux lxplus807.cern.ch 4.18.0-553.56.1.el8_10.x86_64 #1 SMP Mon Jun 2 12:33:13 EDT 2025 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-07-19 21:30:14.855 UTC: 	 Not using Singularity
DEBUG 2025-07-19 21:30:14.855 UTC: 	 Operating System: Red Hat Enterprise Linux 8.10 (Ootpa)
DEBUG 2025-07-19 21:30:14.855 UTC: 	 Executing command: 'status'
DEBUG 2025-07-19 21:30:14.856 UTC: 	 Found CRAB cache file /afs/cern.ch/user/k/kdeverea/.crab3
ERROR 2025-07-19 21:30:14.856 UTC: 	 Error: /afs/cern.ch/user/k/kdeverea/CMSSW_14_1_7/src/HITrackingStudies/HITrackingStudies/test/ppref_Efficiency/crab_Pythia_NoPU_NoTrigger_TuneCP5_QCD_ptHat15_5p36TeV_vzpthatWeight_vzcut_Nominal/crab.log is not a valid CRAB project directory.
ERROR 2025-07-19 21:30:14.856 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/lib/CRABClient/Commands/status.py", line 49, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/lib/CRABClient/Commands/SubCommand.py", line 281, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/lib/CRABClient/Commands/SubCommand.py", line 691, in validateOptions
    raise ConfigurationException(msg)
CRABClient.ClientExceptions.ConfigurationException: [91mError[0m: /afs/cern.ch/user/k/kdeverea/CMSSW_14_1_7/src/HITrackingStudies/HITrackingStudies/test/ppref_Efficiency/crab_Pythia_NoPU_NoTrigger_TuneCP5_QCD_ptHat15_5p36TeV_vzpthatWeight_vzcut_Nominal/crab.log is not a valid CRAB project directory.
INFO 2025-07-19 21:30:14.859 UTC: 	 Log file is /afs/cern.ch/user/k/kdeverea/CMSSW_14_1_7/src/HITrackingStudies/HITrackingStudies/test/crab.log
DEBUG 2025-07-19 22:40:07.124 UTC: 	 CRAB Client version: v3.250522
DEBUG 2025-07-19 22:40:07.125 UTC: 	 Running on: Linux lxplus807.cern.ch 4.18.0-553.56.1.el8_10.x86_64 #1 SMP Mon Jun 2 12:33:13 EDT 2025 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-07-19 22:40:07.125 UTC: 	 Not using Singularity
DEBUG 2025-07-19 22:40:07.125 UTC: 	 Operating System: Red Hat Enterprise Linux 8.10 (Ootpa)
DEBUG 2025-07-19 22:40:07.125 UTC: 	 Executing command: 'submit'
DEBUG 2025-07-19 22:40:07.125 UTC: 	 Found CRAB cache file /afs/cern.ch/user/k/kdeverea/.crab3
INFO 2025-07-19 22:40:07.126 UTC: 	 Will use CRAB configuration file crab_config_pp.py
DEBUG 2025-07-19 22:40:07.126 UTC: 	 Loading CRAB configuration file.
DEBUG 2025-07-19 22:40:07.141 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2025-07-19 22:40:07.142 UTC: 	 Working area '/afs/cern.ch/user/k/kdeverea/CMSSW_14_1_7/src/HITrackingStudies/HITrackingStudies/test/ppref_Efficiency/crab_Pythia_NoPU_NoTrigger_TuneCP5_QCD_ptHat15_5p36TeV_vzpthatWeight_vzcut_Nominal' already exists 
Please change the requestName in the config file
ERROR 2025-07-19 22:40:07.142 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/lib/CRABClient/Commands/SubCommand.py", line 328, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/afs/cern.ch/user/k/kdeverea/CMSSW_14_1_7/src/HITrackingStudies/HITrackingStudies/test/ppref_Efficiency/crab_Pythia_NoPU_NoTrigger_TuneCP5_QCD_ptHat15_5p36TeV_vzpthatWeight_vzcut_Nominal' already exists 
Please change the requestName in the config file
INFO 2025-07-19 22:40:07.145 UTC: 	 Log file is /afs/cern.ch/user/k/kdeverea/CMSSW_14_1_7/src/HITrackingStudies/HITrackingStudies/test/crab.log
DEBUG 2025-07-23 15:25:59.396 UTC: 	 CRAB Client version: v3.250522
DEBUG 2025-07-23 15:25:59.396 UTC: 	 Running on: Linux lxplus802.cern.ch 4.18.0-553.58.1.el8_10.x86_64 #1 SMP Thu Jun 12 14:27:07 EDT 2025 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-07-23 15:25:59.396 UTC: 	 Not using Singularity
DEBUG 2025-07-23 15:25:59.396 UTC: 	 Operating System: Red Hat Enterprise Linux 8.10 (Ootpa)
DEBUG 2025-07-23 15:25:59.396 UTC: 	 Executing command: 'submit'
DEBUG 2025-07-23 15:25:59.396 UTC: 	 Found CRAB cache file /afs/cern.ch/user/k/kdeverea/.crab3
INFO 2025-07-23 15:25:59.522 UTC: 	 Will use CRAB configuration file crab_config_pp.py
DEBUG 2025-07-23 15:25:59.522 UTC: 	 Loading CRAB configuration file.
DEBUG 2025-07-23 15:25:59.556 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2025-07-23 15:25:59.556 UTC: 	 Invalid CRAB configuration: A local DBS instance 'phys03' was specified for reading an input dataset of tier GEN-SIM-RECODEBUG.
Datasets of tier different than USER must be read from the global DBS instance; this is, set Data.inputDBS = 'global'.
If Data.inputDBS would not be specified, the default 'global' ('https://cmsweb.cern.ch/dbs/prod/global/DBSReader') would be used.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2025-07-23 15:25:59.556 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/lib/CRABClient/Commands/SubCommand.py", line 326, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/lib/CRABClient/Commands/SubCommand.py", line 95, in loadConfig
    raise ConfigurationException(configmsg)
CRABClient.ClientExceptions.ConfigurationException: Invalid CRAB configuration: A local DBS instance 'phys03' was specified for reading an input dataset of tier GEN-SIM-RECODEBUG.
Datasets of tier different than USER must be read from the global DBS instance; this is, set Data.inputDBS = 'global'.
If Data.inputDBS would not be specified, the default 'global' ('https://cmsweb.cern.ch/dbs/prod/global/DBSReader') would be used.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
INFO 2025-07-23 15:25:59.581 UTC: 	 Log file is /afs/cern.ch/user/k/kdeverea/CMSSW_14_1_7/src/HITrackingStudies/HITrackingStudies/test/crab.log
DEBUG 2025-07-23 15:29:51.588 UTC: 	 CRAB Client version: v3.250522
DEBUG 2025-07-23 15:29:51.588 UTC: 	 Running on: Linux lxplus802.cern.ch 4.18.0-553.58.1.el8_10.x86_64 #1 SMP Thu Jun 12 14:27:07 EDT 2025 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-07-23 15:29:51.588 UTC: 	 Not using Singularity
DEBUG 2025-07-23 15:29:51.589 UTC: 	 Operating System: Red Hat Enterprise Linux 8.10 (Ootpa)
DEBUG 2025-07-23 15:29:51.589 UTC: 	 Executing command: 'submit'
DEBUG 2025-07-23 15:29:51.589 UTC: 	 Found CRAB cache file /afs/cern.ch/user/k/kdeverea/.crab3
INFO 2025-07-23 15:29:51.589 UTC: 	 Will use CRAB configuration file crab_config_pp.py
DEBUG 2025-07-23 15:29:51.589 UTC: 	 Loading CRAB configuration file.
DEBUG 2025-07-23 15:29:51.594 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2025-07-23 15:29:51.594 UTC: 	 Working area '/afs/cern.ch/user/k/kdeverea/CMSSW_14_1_7/src/HITrackingStudies/HITrackingStudies/test/ppref_Efficiency/crab_QCD_pThat-15to1200_TuneCP5_5p36TeV_pythia8_vzpthatWeight_vzcut_Nominal' already exists 
Please change the requestName in the config file
ERROR 2025-07-23 15:29:51.594 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/lib/CRABClient/Commands/SubCommand.py", line 328, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/afs/cern.ch/user/k/kdeverea/CMSSW_14_1_7/src/HITrackingStudies/HITrackingStudies/test/ppref_Efficiency/crab_QCD_pThat-15to1200_TuneCP5_5p36TeV_pythia8_vzpthatWeight_vzcut_Nominal' already exists 
Please change the requestName in the config file
INFO 2025-07-23 15:29:51.602 UTC: 	 Log file is /afs/cern.ch/user/k/kdeverea/CMSSW_14_1_7/src/HITrackingStudies/HITrackingStudies/test/crab.log
DEBUG 2025-07-24 17:53:49.380 UTC: 	 CRAB Client version: v3.250522
DEBUG 2025-07-24 17:53:49.380 UTC: 	 Running on: Linux lxplus806.cern.ch 4.18.0-553.56.1.el8_10.x86_64 #1 SMP Mon Jun 2 12:33:13 EDT 2025 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-07-24 17:53:49.381 UTC: 	 Not using Singularity
DEBUG 2025-07-24 17:53:49.381 UTC: 	 Operating System: Red Hat Enterprise Linux 8.10 (Ootpa)
DEBUG 2025-07-24 17:53:49.381 UTC: 	 Executing command: 'submit'
DEBUG 2025-07-24 17:53:49.381 UTC: 	 Found CRAB cache file /afs/cern.ch/user/k/kdeverea/.crab3
INFO 2025-07-24 17:53:49.382 UTC: 	 Will use CRAB configuration file crab_config_pp.py
DEBUG 2025-07-24 17:53:49.382 UTC: 	 Loading CRAB configuration file.
DEBUG 2025-07-24 17:53:49.383 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2025-07-24 17:53:49.383 UTC: 	 Working area '/afs/cern.ch/user/k/kdeverea/CMSSW_14_1_7/src/HITrackingStudies/HITrackingStudies/test/ppref_Efficiency/crab_QCD_pThat-15to1200_TuneCP5_5p36TeV_pythia8_vzpthatWeight_vzcut_Nominal_byPdgId' already exists 
Please change the requestName in the config file
ERROR 2025-07-24 17:53:49.383 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/lib/CRABClient/Commands/SubCommand.py", line 328, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/afs/cern.ch/user/k/kdeverea/CMSSW_14_1_7/src/HITrackingStudies/HITrackingStudies/test/ppref_Efficiency/crab_QCD_pThat-15to1200_TuneCP5_5p36TeV_pythia8_vzpthatWeight_vzcut_Nominal_byPdgId' already exists 
Please change the requestName in the config file
INFO 2025-07-24 17:53:49.394 UTC: 	 Log file is /afs/cern.ch/user/k/kdeverea/CMSSW_14_1_7/src/HITrackingStudies/HITrackingStudies/test/crab.log
