DEBUG 2025-07-28 18:35:21.613 UTC: 	 CRAB Client version: v3.250522
DEBUG 2025-07-28 18:35:21.613 UTC: 	 Running on: Linux lxplus807.cern.ch 4.18.0-553.56.1.el8_10.x86_64 #1 SMP Mon Jun 2 12:33:13 EDT 2025 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-07-28 18:35:21.613 UTC: 	 Not using Singularity
DEBUG 2025-07-28 18:35:21.613 UTC: 	 Operating System: Red Hat Enterprise Linux 8.10 (Ootpa)
DEBUG 2025-07-28 18:35:21.613 UTC: 	 Executing command: 'submit'
DEBUG 2025-07-28 18:35:21.614 UTC: 	 Found CRAB cache file /afs/cern.ch/user/k/kdeverea/.crab3
INFO 2025-07-28 18:35:21.616 UTC: 	 Will use CRAB configuration file crab_config_OO.py
DEBUG 2025-07-28 18:35:21.616 UTC: 	 Loading CRAB configuration file.
DEBUG 2025-07-28 18:35:21.637 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2025-07-28 18:35:21.637 UTC: 	 Working area '/afs/cern.ch/user/k/kdeverea/CMSSW_15_0_8/src/HITrackingStudies/HITrackingStudies/test/OO_Efficiency/crab_MinBias_OO_5p36TeV_hijing_Nominal_byPdgId' already exists 
Please change the requestName in the config file
ERROR 2025-07-28 18:35:21.637 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/lib/CRABClient/Commands/SubCommand.py", line 328, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/afs/cern.ch/user/k/kdeverea/CMSSW_15_0_8/src/HITrackingStudies/HITrackingStudies/test/OO_Efficiency/crab_MinBias_OO_5p36TeV_hijing_Nominal_byPdgId' already exists 
Please change the requestName in the config file
INFO 2025-07-28 18:35:21.666 UTC: 	 Log file is /afs/cern.ch/user/k/kdeverea/CMSSW_15_0_8/src/HITrackingStudies/HITrackingStudies/test/crab.log
DEBUG 2025-07-29 13:23:50.359 UTC: 	 CRAB Client version: v3.250522
DEBUG 2025-07-29 13:23:50.359 UTC: 	 Running on: Linux lxplus800.cern.ch 4.18.0-553.58.1.el8_10.x86_64 #1 SMP Thu Jun 12 14:27:07 EDT 2025 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-07-29 13:23:50.359 UTC: 	 Not using Singularity
DEBUG 2025-07-29 13:23:50.359 UTC: 	 Operating System: Red Hat Enterprise Linux 8.10 (Ootpa)
DEBUG 2025-07-29 13:23:50.359 UTC: 	 Executing command: 'submit'
DEBUG 2025-07-29 13:23:50.360 UTC: 	 Found CRAB cache file /afs/cern.ch/user/k/kdeverea/.crab3
ERROR 2025-07-29 13:23:50.366 UTC: 	 CRAB configuration file crabConfig.py not found.
ERROR 2025-07-29 13:23:50.366 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/lib/CRABClient/Commands/SubCommand.py", line 326, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/lib/CRABClient/Commands/SubCommand.py", line 52, in loadConfig
    raise ConfigurationException("CRAB configuration file %s not found." % (configname))
CRABClient.ClientExceptions.ConfigurationException: CRAB configuration file crabConfig.py not found.
INFO 2025-07-29 13:23:50.389 UTC: 	 Log file is /afs/cern.ch/user/k/kdeverea/CMSSW_15_0_8/src/HITrackingStudies/HITrackingStudies/test/crab.log
DEBUG 2025-07-29 19:52:01.007 UTC: 	 CRAB Client version: v3.250522
DEBUG 2025-07-29 19:52:01.008 UTC: 	 Running on: Linux lxplus810.cern.ch 4.18.0-553.58.1.el8_10.x86_64 #1 SMP Thu Jun 12 14:27:07 EDT 2025 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-07-29 19:52:01.008 UTC: 	 Not using Singularity
DEBUG 2025-07-29 19:52:01.008 UTC: 	 Operating System: Red Hat Enterprise Linux 8.10 (Ootpa)
DEBUG 2025-07-29 19:52:01.008 UTC: 	 Executing command: 'checkwrite'
DEBUG 2025-07-29 19:52:01.008 UTC: 	 Found CRAB cache file /afs/cern.ch/user/k/kdeverea/.crab3
WARNING 2025-07-29 19:52:01.008 UTC: 	 Warning: 'crab checkwrite' command takes no arguments, 1 given. Ignoring arguments ['T2_CH_CERN'].
DEBUG 2025-07-29 19:52:01.008 UTC: 	 Checking credentials
DEBUG 2025-07-29 19:52:01.009 UTC: 	 Found proxy file /tmp/x509up_u161760
DEBUG 2025-07-29 19:52:01.009 UTC: 	 Making sure it has proper VOMS extension
DEBUG 2025-07-29 19:52:01.009 UTC: 	 Executing command :
 voms-proxy-info --vo --file /tmp/x509up_u161760
DEBUG 2025-07-29 19:52:01.580 UTC: 	 output : cms

 error: 
 retcode : 0
DEBUG 2025-07-29 19:52:01.580 UTC: 	 Getting proxy life time left
DEBUG 2025-07-29 19:52:01.581 UTC: 	 Executing command :
 voms-proxy-info --actimeleft --timeleft --file /tmp/x509up_u161760
DEBUG 2025-07-29 19:52:02.067 UTC: 	 output : 42985
42984

 error: 
 retcode : 0
DEBUG 2025-07-29 19:52:02.067 UTC: 	 Proxy valid for 11:56:24 hours
DEBUG 2025-07-29 19:52:02.067 UTC: 	 Retrieving username ...
DEBUG 2025-07-29 19:52:02.067 UTC: 	 Retrieving username from CRIC...
DEBUG 2025-07-29 19:52:02.810 UTC: 	 username is kdeverea
INFO 2025-07-29 19:52:03.935 UTC: 	 Rucio client intialized for account kdeverea
ERROR 2025-07-29 19:52:03.935 UTC: 	 Error: Please specify the site where to check the write permissions. Use the --site option.
ERROR 2025-07-29 19:52:03.935 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/lib/CRABClient/Commands/checkwrite.py", line 22, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/lib/CRABClient/Commands/SubCommand.py", line 403, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/lib/CRABClient/Commands/checkwrite.py", line 356, in validateOptions
    raise ex
CRABClient.ClientExceptions.MissingOptionException: [91mError[0m: Please specify the site where to check the write permissions. Use the --site option.
INFO 2025-07-29 19:52:03.948 UTC: 	 Log file is /afs/cern.ch/user/k/kdeverea/CMSSW_15_0_8/src/HITrackingStudies/HITrackingStudies/test/crab.log
DEBUG 2025-08-01 19:00:46.843 UTC: 	 CRAB Client version: v3.250522
DEBUG 2025-08-01 19:00:46.844 UTC: 	 Running on: Linux lxplus811.cern.ch 4.18.0-553.63.1.el8_10.x86_64 #1 SMP Fri Jul 18 06:13:44 EDT 2025 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-08-01 19:00:46.844 UTC: 	 Not using Singularity
DEBUG 2025-08-01 19:00:46.844 UTC: 	 Operating System: Red Hat Enterprise Linux 8.10 (Ootpa)
DEBUG 2025-08-01 19:00:46.844 UTC: 	 Executing command: 'submit'
DEBUG 2025-08-01 19:00:46.844 UTC: 	 Found CRAB cache file /afs/cern.ch/user/k/kdeverea/.crab3
INFO 2025-08-01 19:00:46.845 UTC: 	 Will use CRAB configuration file crab_config_NeNe.py
DEBUG 2025-08-01 19:00:46.845 UTC: 	 Loading CRAB configuration file.
DEBUG 2025-08-01 19:00:46.863 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2025-08-01 19:00:46.864 UTC: 	 Working area '/afs/cern.ch/user/k/kdeverea/CMSSW_15_0_8/src/HITrackingStudies/HITrackingStudies/test/NeNe_Efficiency/crab_MinBias_NeNe_5p36TeV_hijing_Nominal_byPdgId' already exists 
Please change the requestName in the config file
ERROR 2025-08-01 19:00:46.864 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/lib/CRABClient/Commands/SubCommand.py", line 328, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/afs/cern.ch/user/k/kdeverea/CMSSW_15_0_8/src/HITrackingStudies/HITrackingStudies/test/NeNe_Efficiency/crab_MinBias_NeNe_5p36TeV_hijing_Nominal_byPdgId' already exists 
Please change the requestName in the config file
INFO 2025-08-01 19:00:46.882 UTC: 	 Log file is /afs/cern.ch/user/k/kdeverea/CMSSW_15_0_8/src/HITrackingStudies/HITrackingStudies/test/crab.log
